name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [master]
  push:
    tags: [v*.*.*]

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' && 
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=raw,value=latest
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
